apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ui-deployment
spec:
  replicas: 2 # 안정성을 위해 2개의 파드를 실행합니다.
  selector:
    matchLabels:
      app: front-ui
  template:
    metadata:
      labels:
        app: front-ui
    spec:
      containers:
      - name: front-ui-app
        image: cuecode.kr.ncr.ntruss.com/front-ui:latest # CI/CD 파이프라인에서 빌드한 이미지를 사용합니다.
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
