apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ui-deployment
spec:
  replicas: 2 # 안정성을 위해 2개의 파드를 실행합니다.
  selector:
    matchLabels:
      app: front-ui
  template:
    metadata:
      labels:
        app: front-ui
    spec:
      containers:
      - name: front-ui-app
        image: <NCP Container Registry 주소>/front-ui:latest # CI/CD 파이프라인에서 빌드한 이미지를 사용합니다.
        ports:
        - containerPort: 8080
