#spring.application.name=EurekaServer

server:
  port: 8761   # Eureka Server? ??? ?? ??

spring:
  application:
    name: discoverservice   # ??? ??(Eureka Server ?? ?? ??)


eureka:
  server:
    enable-self-preservation: true  # ?? ?? ??. ???? ?? ? ??? ??? ??? ???
    expected-client-renewal-interval-seconds: 100 # ?????? ???? ??? ?? ??
    eviction-interval-timer-in-ms: 600   # ??? ????? ???? ??(ms)
    renewal-percent-threshold: 0.85     # ?????? ??? ???

  client:
    register-with-eureka: false  # Eureka ?? ??? Eureka? ???? ??
    fetch-registry: false        # ?? Eureka ????? ?????? ???? ??

management:
  endpoints:
    web:
      exposure:
        include: "*"   # ?? ?? ????? (/actuator/health ?) ??
