server:
  port: 13000

spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888/"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    gateway:
      routes:
        - id: user-service-user-reg
          uri: http://localhost:11000
          predicates:
            - Path=/user/reg/**
          filters:
            - StripPrefix=1
        - id: user-service-reg
          uri: http://localhost:11000
          predicates:
            - Path=/reg/**

logging:
  level:
    root: INFO
