apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 2 # 안정성을 위해 2개의 파드를 실행합니다.
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-app
        image: cuecode.kr.ncr.ntruss.com/api-gateway:latest # CI/CD 파이프라인에서 빌드한 이미지를 사용합니다.
        ports:
        - containerPort: 13000
        envFrom:
        - secretRef:
            # 게이트웨이의 JWT 토큰 검증에 필요한 비밀키를 담은 Secret
            name: jwt-secret 
