apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  replicas: 1 # 설정 서버는 보통 1개만 실행해도 충분합니다.
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server-app
        image: <NCP Container Registry 주소>/config-server:latest
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: git-ssh-key
          mountPath: /root/.ssh # 컨테이너의 ssh 키 경로에 볼륨을 마운트합니다.
          readOnly: true
      volumes:
      - name: git-ssh-key
        secret:
          # NCP SourceCommit에 접근하기 위한 SSH 키를 담은 Secret의 이름
          secretName: sourcecommit-ssh-secret 
          defaultMode: 0400 # 키 파일의 권한 설정
