server:
  port : 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chloe-soyeon/CueCode-Config
          default-label: master
          search-paths: msa

